# 新虫子



## 报错信息

```
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select
```



## 报错原因

这个问题显然是tensor数据格式不对造成的。显然pytorch希望它对两个tensor进行计算时，两个tensor的数据格式是一致的，并且处于同一个设备，要么是CPU，要么是GPU。因此，**当部分数据在CPU上，但另一部分的数据在GPU上**，pytorch就无情地报错了。



## 出现问题的原因

- 部分数据（模型+训练样本）载入GPU，部分数据未载入GPU，仍然保留在CPU上。
  - 模型载入了GPU，而输入样本未载入（常见情况）；
  - 在模型内部定义了新的tensor，但未载入GPU。当按照常见情形处理时，会发现始终无法解决。

## 解决方案

- Print大法，找到报错位置的tensor，打印其格式，确定这个tensor和模型或者其他tensor处于同一设备。